pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                // Compile the Java source file
                sh 'javac HelloWorld.java'
            }
        }

        stage('Run') {
            steps {
                // Run the compiled Java class
                sh 'java HelloWorld'
            }
        }
    }
}

